### ISSUE TITLE
The CDS extraction script on README seems outdated.

### ISSUE THREAD

**Issue by camilogarciabotero** [althonos/gb-io.py#48]
Hi, 

I was trying to run the suggested script from the README:

```python
import gb_io

with open("tests/data/AY048670.1.faa", "w") as dst:
    for record in gb_io.iter("tests/data/AY048670.1.gb"):
        for feature in filter(lambda feat: feat.type == "CDS", record.features):
            qualifiers = feature.qualifiers.to_dict()
            dst.write(">{}\n".format(qualifiers["locus_tag"][0]))
            dst.write("{}\n".format(qualifiers["translation"][0]))
```

And I got the following error:

```python
Traceback (most recent call last):
  File "test.py", line 38, in <module>
    main()
  File "test.py", line 28, in main
    for feature in filter(lambda feat: feat.type == "CDS", record.features):
  File "test.py", line 28, in <lambda>
    for feature in filter(lambda feat: feat.type == "CDS", record.features):
AttributeError: 'gb_io.Feature' object has no attribute 'type'
```

I guess that from the latest updates, the `gb_io.Feature` works differently from the version the example was created with. So, probably this line should be different:

```python
for feature in filter(lambda feat: feat.type == "CDS", record.features):
```

Best.

**Comment by althonos** [comment]
Thanks Camilo, I have updated the example with the new API.
